puts "The students of Villains Academy"
puts "--------------------------------"
puts "Darth Vader"
puts "Elmo"
puts "The Joker"
puts "Thanos"
puts "Lex Luther"
puts "Magneto"
puts "Medusa"
puts "Poison Ivy"
puts "Joffrey Baratheon"
puts "Negan"
